### ISSUE TITLE
Crash on latest PR

### ISSUE THREAD

**Issue by jackson-57** [macmv/tilemap-editor#2]
Same error across Linux, Windows, and macOS. https://github.com/macmv/tilemap-editor/commit/50397d37e9de3930706702a92f42456faf45edbb is the culprit.
Error is below:
```$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    win = MyWindow()
  File "main.py", line 26, in __init__
    tileset = tileset_module.create(16, 16)
  File "C:\msys64\home\jacks\tilemap-editor\tileset.py", line 152, in create
    return Tileset(width, height)
  File "C:\msys64\home\jacks\tilemap-editor\tileset.py", line 25, in __init__
    self.add()
TypeError: add() missing 1 required positional argument: 'event'
```

**Comment by macmv** [comment]
I'll be working on that while I add the new file dialog, and it should be fixed during that time.

**Comment by jackson-57** [comment]
Sounds good! Happy to see development pick up.
